[project]
name = "open-ai-agent-sdk-sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "markdown>=3.8",
    "openai-agents[litellm]>=0.0.17",
    "pygments>=2.19.1",
]
